### ISSUE TITLE
panic at 'not implemented'

### ISSUE THREAD

**Issue by charlesxsh** [simnalamburt/obj-rs#49]
For given input file:
[in.zip](https://github.com/simnalamburt/obj-rs/files/7239750/in.zip)

The following code
```rust
use std::io::Cursor;
fn main(){
    let filepath = "<input file>"
    let data = std::fs::read(filepath).unwrap();
    let cursor = Cursor::new(data);
    let _: Result<obj::Obj, obj::ObjError> = obj::load_obj(cursor);
}
```

reports
```
thread 'main' panicked at 'not implemented', ...
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: std::panicking::rust_panic_with_hook
   6: std::panicking::begin_panic
             at /.../code/rust-compiler/src/libstd/panicking.rs:456
   7: obj::raw::object::parse_obj::{{closure}}
             at /.../code/rust-compiler/src/libstd/macros.rs:13
   8: obj::raw::lexer::lex
             at /.../.cargo/registry/src/github.com-1ecc6299db9ec823/obj-rs-0.6.3/src/raw/lexer.rs:40
   9: obj::raw::object::parse_obj
             at /home/szx5097/.cargo/registry/src/github.com-1ecc6299db9ec823/obj-rs-0.6.3/src/raw/object.rs:102
  10: obj::load_obj
             at /home/szx5097/.cargo/registry/src/github.com-1ecc6299db9ec823/obj-rs-0.6.3/src/lib.rs:50
...
```

**Comment by simnalamburt** [comment]
Yeah some syntaxes are not implemented yet..
